name: build-htms
description: Build an htms project with a GitHub action
author: Trevor Nichols
branding:
  icon: arrow-right
  color: blue
inputs:
  input:
    description: 'Source directory to build'
    required: false
    default: './src'
  output:
    description: 'Output directory of build'
    required: false
    default: './out'
  config:
    description: 'Config file to use'
    required: false
    default: 'none'
  branch:
    description: 'Branch, commit hash, or tag of htms to use'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v30
    - name: Build Project
      shell: bash
      run: |
        nix run --experimental-features "nix-command flakes" "github:tnichols217/htms#htms/${{ inputs.branch }}" -- --input "${{ inputs.input }}" --output "${{ inputs.output }}" --config "${{ inputs.config }}"
